version: "3.9"  
services:
  web_api:
    image: decoderslash
    container_name: app
    ports:
      - "5000:80"
    environment:
      - Volume=/src/
    volumes:
      - myapp:/src/
  sql:
    image: decodersql
    container_name: decoderslash_erp_db #REMEMBER TO POINT YOUR DB STRING TO THIS NAME 
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    user: root
    volumes:
     - myapp:/src/ 
volumes:
  myapp: